server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: false # Evita doble compresión detrás de API Gateway

app:
  base-path: ${BASE_PATH:} # En API Gateway usa BASE_PATH=/dev

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    # Sirve explícitamente el HTML
    path: /swagger-ui/index.html
    # Usa SOLO 'url' (no 'config-url') para evitar problemas detrás de API GW
    url: ${app.base-path}/v3/api-docs
    disable-swagger-default-url: true
    oauth2-redirect-url: ${app.base-path}/swagger-ui/oauth2-redirect.html
    enabled: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    show-extensions: true
    show-common-extensions: true

  override-with-generic-response: false
  cache:
    disabled: true
  show-actuator: false

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.servlet.view.RedirectView: INFO
    com.example.demo.platform.config.ApiGatewayBasePathFilter: INFO

