server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: false
  servlet:
    context-path: ${BASE_PATH:} # <-- En Lambda pon BASE_PATH=/dev

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    # Mantén el UI en /swagger-ui; Spring redirige solo si hace falta
    path: /swagger-ui
    # Apunta al spec incluyendo el context-path
    url: ${server.servlet.context-path}/v3/api-docs
    disable-swagger-default-url: true
    oauth2-redirect-url: ${server.servlet.context-path}/swagger-ui/oauth2-redirect.html
    enabled: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    show-extensions: true
    show-common-extensions: true

  override-with-generic-response: false
  cache:
    disabled: true
  show-actuator: false

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.servlet.view.RedirectView: INFO
    com.example.demo.platform.config.ApiGatewayBasePathFilter: INFO

