server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: false # evita doble compresión en Lambda/API GW

app:
  base-path: ${BASE_PATH:} # en API GW: BASE_PATH=/dev

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    # Deja el UI en /swagger-ui; springdoc redirige él mismo a /swagger-ui/index.html
    path: /swagger-ui

    # Usa SOLO 'url' (evita config-url para no romper inicialización detrás de API GW)
    url: ${app.base-path}/v3/api-docs

    disable-swagger-default-url: true
    oauth2-redirect-url: ${app.base-path}/swagger-ui/oauth2-redirect.html
    enabled: true
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    show-extensions: true
    show-common-extensions: true

  override-with-generic-response: false
  cache:
    disabled: true
  show-actuator: false

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.servlet.view.RedirectView: INFO
    com.example.demo.platform.config.ApiGatewayBasePathFilter: INFO

