name: Trigger Jenkins Job

on:
  push:
    branches:
      - "dev"
      - "staging"
      - "main"
      - "main-setup"
  workflow_dispatch:

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get branch name and build Jenkins URL
      - name: Get branch name and build Jenkins URL
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME#aiccra-}
          JENKINS_URL="https://automation.prms.cgiar.org/job/marlo-dev-v2/build"
          echo "Jenkins job URL for the branch $BRANCH_NAME is: $JENKINS_URL"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      # Step 2: Execute the curl command to trigger the job in Jenkins with the dynamically built URL
      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_URL: ${{ env.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
